version: '3.0'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: ordermanagementdb
       MYSQL_USER: finlexuser
       MYSQL_PASSWORD: finlexpassword
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   ordermanagerapp:
     depends_on:
       - db
     image: finlex/ordermanager:runtime
     build:
       context: .
     ports:
       - "8080:5000"

volumes:
    dbdata: